export const palette = {
  black: "#000000",
  white: "#FFFFFF",
  red: "#FF0000",
  purpleHeart: '#6035D0',
  keppelColor: '#36AFAD',
  tradewind: '#67a6b3',
  texasRose: '#fdc14d',
  waterLeaf: '#a6e8de',
  persianGreen: "#009F9C",
  transparent: 'transparent',
  bittersweet: "#FF6E6E",
  heliotrope: '#AD6EFF',
  macaroni: "#FFB26E",
  hotPink: '#FF6EC0',
}
