//login

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

//auth
export const AUTH_REQUEST = 'AUTH_REQUEST';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

//market
export const LIST_NFTS_REQUEST = 'LIST_NFTS_REQUEST';
export const LIST_NFTS_SUCCESS = 'LIST_NFTS_SUCCESS';

//filter
export const FILTER_MARKET ='FILTER_MARKET';
export const BUY_NFTS = 'BUY_NFTS';

//PROFILE
export const PROFILE_REQUEST = 'PROFILE_REQUEST';
export const PROFILE_SUCCESS = 'PROFILE_SUCCESS';

//run history
export const RUN_HISTORY_REQUEST = 'RUN_HISTORY_REQUEST';
export const RUN_HISTORY_SUCCESS = 'RUN_HISTORY_SUCCESS';

//transaction
export const TRANSACTION_REQUEST = 'TRANSACTION_REQUEST';
export const TRANSACTION_SECCESS = 'TRANSACTION_SECCESS';

//mint
export const MINNT_CHOOSE_REQUEST = 'MINNT_CHOOSE_REQUEST';
export const MINNT_CHOOSE_SUCCESS = 'MINNT_CHOOSE_SUCCESS';

export const MINT_FEE_REQUEST = 'MINT_FEE_REQUEST';
export const MINT_FEE_SUCCESS = 'MINT_FEE_SUCCESS';

export const MINT_REQUEST = 'MINT_REQUEST';
export const MINT_SUCCESS = 'MINT_SUCCESS';

export const SELECT_ITEM = 'SELECT_ITEM';

//sneaker
export const SNEAKER_LIST_REQUEST = 'SNEAKER_LIST_REQUEST';
export const SNEAKER_LIST_SUCCESS = 'SNEAKER_LIST_SUCCESS';

export const SNEAKER_DETAIL_REQUEST = 'SNEAKER_DETAIL_REQUEST';
export const SNEAKER_DETAIL_SUCCESS = 'SNEAKER_DETAIL_SUCCESS';

export const LEVELUP = 'LEVEL_UP';
export const ATTRUP = 'ATTRUP';
export const REPAIR = 'REPAIR';

export const START = 'START';
export const STOP = 'STOP';
export const STOP_REQUEST = 'STOP_REQUEST';
export const STOP_SUCCESS = 'STOP_SUCCESS';